spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/task_platform
spring.datasource.username=${DB_USERNAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379